Main menu eerste opzet...
brambekkers/SocketIO pull request #8
Opened 2018-10-19 16:55 UTC by brambekkers

He Thijs, 

Zou jij dit willen bekijken? Over de achtergrond ben ik nog niet te spreken.

En als ik buttons switch moet ik dan de oude destroyen?

2018-10-21 19:26 UTC, thijsdaniels requested changes

2018-10-21 19:26 UTC, thijsdaniels commented on client/src/scenes/levels/MainMenu.js
> +        this.logo.setPosition(width / 2, height / 2);
Dit kan ook met CSS das een stuk beter qua performance. Als je googlet naar flexbox vind je m wel

2018-10-21 19:26 UTC, thijsdaniels commented on client/src/scenes/levels/MainMenu.js
> +    createButtonBackground(scene, button){
Eigenlijk zou het mooier zijn om een class Button extends Sprite te maken.

Dan kun je hier doen:

this.someButton = new Button(this, options, () => { alert('button was clicked'); });

En kan de button zelf de rest (zoals hover state en sounds) afhandelen, zodat je dat niet elke keer opnieuw hoeft te definiëren.

2018-10-21 19:26 UTC, thijsdaniels commented on client/src/scenes/levels/MainMenu.js
> +    muteMusic(boolean){
Deze is nog niet af denk ik?

Je wil hier eigenlijk een of andere globale 'volume' setting aanpassen, zodat LevelTwo zijn eigen BGM ook zachter of uit kan zetten. Voor nu kan die wel even op de window (window.settings.audio.volume.bgm = 0) of zo. Maar uiteindelijk zullen we daar classes voor moeten maken (e.g. een Settings en AudioManager). Zodat LevelTwo in z'n create() method AudioManager.playBGM('someTrack') kan doen, en dat de audio manager dan zelf eerst de al spelende BGM (van MainMenu) stopt. En AudioManager kan dan aan de hand van Settings.audio.volume.bgm bepalen hoe hard ie moet.

2018-10-21 19:26 UTC, thijsdaniels commented on client/src/sprites/Player.js
> +        for (let i = 1; i <= 5; i++) {
Zie je dat we nu op 4 plekken het aantal playable characters gebruiken? Zelfs verdeeld over server en client? Dat aantal moet heel erg nodig geabstract worden. "Single point of truth" is een belangrijk concept waarbij  dezelfde data altijd maar 1 keer en door 1 systeem wordt bepaald. Hoe minder dat het geval is, hoe groter de kans op bugs. In dit geval kunnen we het aantal playable characters mooi in de config.js zetten. Zowel de server als de client kan die dan importen waar nodig, en dan kunnen we met 1 variabele alles fixen :)

2018-10-21 19:26 UTC, thijsdaniels commented on client/src/scenes/levels/MainMenu.js
> +export default class Level extends Scene {
Klein detail maar de class name ben je vergeten aan te passen ;)

2018-10-23 13:36 UTC, brambekkers commented on client/src/scenes/levels/MainMenu.js
> +        this.logo.setPosition(width / 2, height / 2);
Ik heb deze inmiddels verwijderd. Is idd beter met css

2018-10-25 16:34 UTC, brambekkers commented on client/src/sprites/Player.js
> +        for (let i = 1; i <= 5; i++) {
Waar zetten we die config.js?

2018-10-27 10:42 UTC, merged